# Generated by Django 5.2.5 on 2025-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('drugs', 'drugs'), ('fruits', 'fruits'), ('food', 'food')], max_length=100)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
